<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Afterthedeadline Config
    |--------------------------------------------------------------------------
    */

    /*
     * API Key (generated by yourself)
     * From their website:
     * "To generate an API key, consider using a short string to identify your application followed by a hash
     * of something unique to the user or installation of AtD"
     *
     * Source: http://www.afterthedeadline.com/api.slp
     */

    'key' => '',

];
